name: kk_advice
description: 68 Bits of Unsolicited Advice from KK

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  share: ^0.6.4+3
  clipboard_manager: ^0.0.4
  rounded_letter: ^0.0.5
  rating_dialog: ^1.0.0
  launch_review: ^2.0.0
  url_launcher: ^5.4.11
  flutter:
    sdk: flutter
  

  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.0.0
  google_fonts: ^1.1.0
  # //https://pub.dev/packages/scrollable_positioned_list#-readme-tab-
  flutter_launcher_icons: ^0.7.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/logo/logo_transparent.png"
  android: true


flutter:
  uses-material-design: true
  fonts:
    - family: Amarante     
      fonts:
        - asset: assets/fonts/Amarante_script.ttf
    - family: BadScript     
      fonts:
        - asset: assets/fonts/BadScript.ttf
    - family: DancingScript     
      fonts:
        - asset: assets/fonts/DancingScript.ttf
    - family: Satisfy     
      fonts:
        - asset: assets/fonts/Satisfy.ttf      
    - family: Typewriter     
      fonts:
        - asset: assets/fonts/VT323.ttf        
    - family: School     
      fonts:
        - asset: assets/fonts/Schoolbell.ttf 
    - family: Gugi     
      fonts:
        - asset: assets/fonts/Gugi.ttf               
    - family: Fondamento     
      fonts:
        - asset: assets/fonts/fondamentoReg.ttf
        - asset: assets/fonts/fondamentoIta.ttf
          style: italic


